name: Go Build and Upload

on:
  push:
    branches:
      - main

env:
  FILE_NAME: hello-server

jobs:
  BuildGo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Go environment
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'
        
    - name: Build for Linux
      run: go build ${{ env.FILE_NAME }}.go
      
    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

  UploadArtifacts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Upload artifact for Linux
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

    - name: Upload artifact for Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe

name: Go Build and Upload

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * 1-6'  # Executa a cada 15 minutos de segunda a sábado
    
