name: Go Build and Upload

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * 1-6'  # Executa a cada 15 minutos de segunda a sábado

env:
  FILE_NAME: hello-server

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Build for Linux
        run: go build ${{ env.FILE_NAME }}.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

  upload-linux-artifact:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - name: Upload artifact for Linux
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}

  upload-windows-artifact:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - name: Upload artifact for Windows
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe

  download-and-run-linux:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Linux artifact
        uses: actions/download-artifact@v2
        with:
          name: linux

      - name: Run the script on Linux
        run: chmod +x ./run.sh && ./run.sh

  download-only-windows:
    runs-on: windows-latest
    needs: build-go
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Windows artifact
        uses: actions/download-artifact@v2
        with:
          name: windows
